config/routes.rb
Rails.application.routes.draw do
  get 'excel_upload/new'

  post 'excel_upload' => 'excel_upload#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/excel_upload_controller.rb
require 'rubyXL'
class ExcelUploadController < ApplicationController
  def new

  end

  def create
  	workbook = RubyXL::Parser.parse(params[:file].path)
  	worksheet = workbook[0]

    worksheet.each { |row|
       row && row.cells.each { |cell|
        val = cell && cell.value
        puts val
      }
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/excel_upload_helper.rb
module ExcelUploadHelper
end

app/views/excel_upload/create.html.erb
<h1>ExcelUpload#create</h1>
<p>Find me in app/views/excel_upload/create.html.erb</p>

app/views/excel_upload/new.html.erb
<h2>Import Products</h2>

<%= form_tag excel_upload_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReaderXl</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>